### ISSUE TITLE
prepare NTU RGB+D dataset

### ISSUE THREAD

**Issue by zhulishun** [haamoon/mmtm#1]
Hi~
This is a great job. I used the nturgbd dataset for the first time. I downloaded the dataset according to your instructions, but I stuck in "change all video clips resolution to 256x256 30fps and copy them to root / NTU / ntrgbd"_ rgb/avi_ 256x256_ 30/ directory.”How can I change all video clips resolution to 256x256 30fps?
Thank you in advance for your answer.

**Comment by haamoon** [comment]
Hi,
I would suggest using ffmpeg for this purpose. You can [scale](https://trac.ffmpeg.org/wiki/Scaling) and [change the frame rate](https://trac.ffmpeg.org/wiki/ChangingFrameRate) in a single command. Also, you might use a script like [this](https://stackoverflow.com/questions/10523415/execute-command-on-all-files-in-a-directory) to convert all the videos.

**Comment by zhulishun** [comment]
thanks a lot.

**Comment by kevinsu628** [comment]
Hello @haamoon , for the resizing part, I am wondering if the video is scaled to a 256x256 with the actual video content resized to 1x1, or still stays 16:9? 
So far, I find that neither gives me the accuracy reported in the paper (inflated resnet gives 79% in my run). 

Below is my video format. Is there anything that looks odd to you? 
Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 256x256 [SAR 1:1 DAR 1:1], 256 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc

Thanks in advance!

**Comment by haamoon** [comment]
Sorry, since this issue was closed I did not receive any notification for your comment. 

The accuracy seems too low even for a single modality. I change the aspect ratio to 1:1 when resizing the video. I use a python function like this:

```
def resize_vid(fn_in, fn_out):
    cap = cv2.VideoCapture(fn_in)
    num_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    heigth = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    width = 256
    height = 256
    video = []
    for fr_idx in range(num_frames):
        ret, frame = cap.read()
        if cap.isOpened():
            frame = cv2.resize(frame, (width,height))
            video.append(frame)
    cap.release()
    video = np.array(video)
    save_video(video, fn_out, fps = 30)
```

Perhaps give this function a try first.

**Comment by kevinsu628** [comment]
> Sorry, since this issue was closed I did not receive any notification for your comment.
> 
> The accuracy seems too low even for a single modality. I change the aspect ratio to 1:1 when resizing the video. I use a python function like this:
> 
> ```
> def resize_vid(fn_in, fn_out):
>     cap = cv2.VideoCapture(fn_in)
>     num_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
>     width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
>     heigth = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
>     width = 256
>     height = 256
>     video = []
>     for fr_idx in range(num_frames):
>         ret, frame = cap.read()
>         if cap.isOpened():
>             frame = cv2.resize(frame, (width,height))
>             video.append(frame)
>     cap.release()
>     video = np.array(video)
>     save_video(video, fn_out, fps = 30)
> ```
> 
> Perhaps give this function a try first.

Thanks for answering the question. Could you elaborate on where the save_video function comes from? 
It seems like most people use a cv2 VideoWritter and write the frame one by one

**Comment by haamoon** [comment]
Yes, you're right:
```
def save_video(vid, name, fps = 24):
    fourcc = cv2.VideoWriter_fourcc(*'MPEG')
    out = cv2.VideoWriter(name,fourcc, fps, (vid.shape[2], vid.shape[1]))

    for i in range(len(vid)):
          out.write(vid[i])
    out.release()
```
